load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "circle",
    srcs = ["circle.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/circle",
    visibility = ["//predix:__subpackages__"],
    deps = ["//predix/internal/domain/user"],
)

go_test(
    name = "circle_test",
    size = "small",
    srcs = ["circle_test.go"],
    data = [
        "//predix/internal/sql:schema.sql",
    ],
    tags = [
        # keep
        "requires-docker",
        "requires-network",
    ],
    deps = [
        ":circle",
        "//predix/internal/domain/user",
    ],
)
