load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//book-arena"])

rust_library(
    name = "lib",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "book_arena_migration",
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
    deps = [
        "@crates//:anyhow",
        "@crates//:sea-orm-migration",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:thiserror",
        "@crates//:tokio",
    ],
)

rust_test(
    name = "lib_test",
    crate = ":lib",
)
