load("@aspect_rules_js//js:defs.bzl", "js_library", "js_run_binary", "js_run_devserver")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//personal_website:astro/package_json.bzl", "bin")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

# This macro expands to a link_npm_package for each third-party package in package.json
npm_link_all_packages(name = "node_modules")

SRCS = [
    "package.json",
    "tsconfig.json",
    "astro.config.ts",
    "//personal_website/src",
    "//personal_website/public",
]

BUILD_DEPS = [":node_modules/" + d for d in [
    "astro",
    "@tailwindcss/vite",
    "tailwindcss",
    "@tailwindcss/typography",
    "daisyui",
    "sharp",
]]

js_library(
    name = "eslintrc",
    srcs = ["eslint.config.js"],
    # prevent conflicting actions when linting
    tags = ["no-lint"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":node_modules/eslint-plugin-astro",
        "//:node_modules/@eslint/js",
        "//:node_modules/typescript-eslint",
    ],
)

bin.astro_binary(
    name = "astro",
    chdir = package_name(),
    # prevents modifying the host machine filesystem
    env = {
        "ASTRO_TELEMETRY_DISABLED": "1",
    },
)

js_run_binary(
    name = "build",
    srcs = SRCS + BUILD_DEPS,
    args = ["build"],
    mnemonic = "AstroBuild",
    out_dirs = ["dist"],
    tool = ":astro",
)

bin.astro_binary(
    name = "dev",
    args = ["dev"],
    chdir = package_name(),
    data = SRCS + BUILD_DEPS,
    # prevents modifying the host machine filesystem
    env = {
        "ASTRO_TELEMETRY_DISABLED": "1",
    },
)

bin.astro_binary(
    name = "preview",
    args = ["preview"],
    chdir = package_name(),
    data = [":build"],
    # prevents modifying the host machine filesystem
    env = {
        "ASTRO_TELEMETRY_DISABLED": "1",
    },
)

pkg_tar(
    name = "caddyfile_layer",
    srcs = ["Caddyfile"],
    package_dir = "/etc/caddy",
)

pkg_tar(
    name = "frontend_layer",
    srcs = [":build"],
    package_dir = "/app",
    strip_prefix = "dist",
)

oci_image(
    name = "image",
    base = "@alpine_caddy",
    entrypoint = [
        "caddy",
        "run",
        "--config",
        "/etc/caddy/Caddyfile",
    ],
    tars = [
        ":caddyfile_layer",
        ":frontend_layer",
    ],
)

oci_load(
    name = "load_image",
    image = ":image",
    repo_tags = ["lowkeylab/personal_website:latest"],
)

oci_push(
    name = "push_image",
    image = ":image",
    remote_tags = ["latest"],
    repository = "ghcr.io/lowkeylab/personal_website",
    visibility = ["//personal_website:__pkg__"],
)
