load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "game_test",
    size = "small",
    srcs = glob(["*.kt"]),
    test_class = "io.lowkeylab.guesstheword.game.GameTest",
    runtime_deps = ["//guess_the_word/src/test:test_runtime_deps"],
    deps = [
        "//guess_the_word/src/main/io/lowkeylab/guesstheword/game",
        "//guess_the_word/src/main/io/lowkeylab/guesstheword/player",
        "//guess_the_word/src/test:test_deps",
    ],
)
