load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "circle",
    srcs = [
        "circle.go",
        "repository.go",
    ],
    importpath = "github.com/lowkeylab/bazel-repo/predix/domain/circle",
    visibility = ["//visibility:public"],
    deps = [
        "//predix/domain/user",
        "@com_github_google_uuid//:uuid",
    ],
)
