load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rest",
    srcs = ["handlers.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/circle/rest",
    visibility = ["//predix:__subpackages__"],
    deps = [
        "//predix/internal/auth",
        "//predix/internal/domain/circle",
        "//predix/internal/domain/circle/service",
        "//predix/internal/domain/circle/sse",
        "//predix/internal/domain/contest",
        "//predix/internal/domain/user",
        "@com_github_gin_contrib_slog//:slog",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "rest_test",
    timeout = "short",
    srcs = ["handlers_test.go"],
    embed = [":rest"],
    tags = [
        # keep
        "requires-docker",
        "requires-network",
    ],
    deps = [
        "//predix/internal/auth",
        "//predix/internal/clock",
        "//predix/internal/db",
        "//predix/internal/domain/circle/repository",
        "//predix/internal/domain/circle/service",
        "//predix/internal/domain/circle/sse",
        "//predix/internal/domain/contest",
        "//predix/internal/domain/contest/repository",
        "//predix/internal/domain/user",
        "//predix/internal/domain/user/repository",
        "//predix/internal/testutil",
        "@com_github_gin_contrib_slog//:slog",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
