load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "repository",
    srcs = [
        "postgres.go",
        "repository.go",
    ],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/user/repository",
    visibility = ["//predix:__subpackages__"],
    deps = [
        "//predix/internal/db",
        "//predix/internal/domain/user",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)

go_test(
    name = "repository_test",
    size = "small",
    srcs = ["postgres_test.go"],
    data = [
        "//predix/internal/sql:schema.sql",
    ],
    tags = [
        # keep
        "requires-docker",
        "requires-network",
    ],
    deps = [
        ":repository",
        "//predix/internal/domain/user",
        "//predix/internal/testutil",
    ],
)
