"""Targets in the repository root"""

load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@gazelle//:def.bzl", "gazelle")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_kotlin//kotlin:core.bzl", "define_kt_toolchain")

# Gazelle Kotlin is too buggy at the moment to be enabled globally
# gazelle:kotlin disabled
# gazelle:js_npm_package_target_name pkg
npm_link_all_packages(name = "node_modules")

alias(
    name = "format",
    actual = "//tools/format",
)

exports_files(
    [
        ".clang-tidy",
        ".ruff.toml",
        ".shellcheckrc",
        "buf.yaml",
        "checkstyle.xml",
        "gazelle_python.yaml",
        "pmd.xml",
        "pyproject.toml",
        ".editorconfig",
        ".ktlint-baseline.xml",
    ],
    visibility = [
        "//tools/format:__pkg__",
        "//tools/lint:__pkg__",
    ],
)

js_library(
    name = "eslintrc",
    srcs = ["eslint.config.mjs"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":node_modules/@eslint/js",
        ":node_modules/typescript-eslint",
    ],
)

js_library(
    name = "prettierrc",
    srcs = ["prettier.config.cjs"],
    visibility = ["//tools/format:__pkg__"],
    deps = [],
)

# Gazelle configuration
gazelle(
    name = "gazelle",
    env = {
        "ENABLE_LANGUAGES": ",".join([
            "starlark",
            "proto",
            "kotlin",
            "js",
        ]),
    },
    gazelle = "@multitool//tools/gazelle",
)

### Kotlin toolchain configuration
define_kt_toolchain(
    name = "kotlin_toolchain",
    jvm_target = "21",
)
