"""Targets in the repository root"""

load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@gazelle//:def.bzl", "DEFAULT_LANGUAGES", "gazelle", "gazelle_binary")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_clojure//rules:tools_deps.bzl", "clojure_gen_srcs")
load("@rules_kotlin//kotlin:core.bzl", "define_kt_toolchain")

npm_link_all_packages(name = "node_modules")

clojure_gen_srcs(name = "clojure_gen_build_files")

exports_files(
    [
        "deps.edn",
    ],
    visibility = ["//visibility:public"],
)

exports_files(
    [
        ".clang-tidy",
        ".ruff.toml",
        ".shellcheckrc",
        "buf.yaml",
        "checkstyle.xml",
        "gazelle_python.yaml",
        "pmd.xml",
        "pyproject.toml",
        ".editorconfig",
        ".ktlint-baseline.xml",
        ".clippy.toml",
    ],
    visibility = [
        "//tools/format:__pkg__",
        "//tools/lint:__pkg__",
    ],
)

js_library(
    name = "eslintrc",
    srcs = ["eslint.config.mjs"],
    # prevent conflicting actions when linting
    tags = ["no-lint"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":node_modules/@eslint/js",
        ":node_modules/typescript-eslint",
    ],
)

js_library(
    name = "prettierrc",
    srcs = ["prettier.config.mjs"],
    # prevent conflicting actions when linting
    tags = ["no-lint"],
    visibility = ["//tools/format:__pkg__"],
    deps = [],
)

js_library(
    name = "stylelintrc",
    srcs = ["stylelint.config.mjs"],
    # prevent conflicting actions when linting
    tags = ["no-lint"],
    visibility = ["//tools/lint:__pkg__"],
    deps = [
        ":node_modules/stylelint",
    ],
)

# Gazelle configuration
# gazelle:exclude githooks/*
# gazelle:exclude personal_website/*
# gazelle:exclude tools/*
# gazelle:exclude angular/*
# gazelle:exclude ktor_tutorial/*
# gazelle:exclude mindreadr/*
# gazelle:exclude nicknamer/*
# gazelle:rust_cargo_lockfile Cargo.lock
# gazelle:rust_crates_prefix @crates//:
gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
)

gazelle_binary(
    name = "gazelle_bin",
    languages = DEFAULT_LANGUAGES + [
        "@contrib_rules_jvm//java/gazelle",
        "@bazel_skylib_gazelle_plugin//bzl",
        "@gazelle_rust//rust_language",
    ],
)

### Kotlin toolchain configuration
define_kt_toolchain(
    name = "kotlin_toolchain",
    jvm_target = "25",
)

### Rust project generation
alias(
    name = "gen_rust_project",
    actual = "@rules_rs//tools/rust_analyzer:gen_rust_project",
)
