"Module file for building projects in lowkeylab"

module(
    name = "bazel-repo",
    version = "0.1.0",
    compatibility_level = 1,
)

bazel_dep(name = "rules_shell", version = "0.6.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "aspect_bazel_lib", version = "2.21.1")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "swagger_ui",
    urls = ["https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.17.14.zip"],
    integrity = "sha256-SBJE0IEgl7Efuu73n3HZQrFxYX+cn5UU5jrL4T5xzNw=",
    strip_prefix = "swagger-ui-5.17.14",
    build_file = "//3rdparty/swagger_ui:BUILD.bazel",
)

# --- Rust Configuration ---
bazel_dep(name = "rules_rust", version = "0.64.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
inject_repo(crate, "swagger_ui", "aspect_bazel_lib")

# Regular dependencies
crate.spec(
    package = "anyhow",
    version = "1.0.99",
)
crate.spec(
    package = "askama",
    version = "0.14.0",
)
crate.spec(
    package = "axum",
    version = "0.8.4",
)
crate.spec(
    features = ["cookie"],
    package = "axum-extra",
    version = "0.10.1",
)
crate.spec(
    package = "chrono",
    version = "0.4.42",
)
crate.spec(
    package = "config",
    version = "0.15.15",
)
crate.spec(
    package = "jsonwebtoken",
    version = "9.3.1",
)
crate.spec(
    features = [
        "sqlx-postgres",
        "runtime-tokio-rustls",
        "macros",
    ],
    package = "sea-orm",
    version = "1.1.16",
)
crate.spec(
    default_features = False,
    features = [
        "runtime-tokio-rustls",
        "sqlx-postgres",
        "cli",
    ],
    package = "sea-orm-migration",
    version = "1.1.0",
)
crate.spec(
    package = "serde",
    version = "1.0.219",
)
crate.spec(
    package = "serde_json",
    version = "1.0",
)
crate.spec(
    package = "serde_yaml",
    version = "0.9.34",
)
crate.spec(
    package = "thiserror",
    version = "2.0.16",
)
crate.spec(
    package = "time",
    version = "0.3.43",
)
crate.spec(
    default_features = False,
    features = [
        "macros",
        "net",
        "rt-multi-thread",
    ],
    package = "tokio",
    version = "1.47.1",
)
crate.spec(
    features = ["util"],
    package = "tower",
    version = "0.5",
)
crate.spec(
    features = [
        "trace",
        "cors",
        "sensitive-headers",
    ],
    package = "tower-http",
    version = "0.6.6",
)
crate.spec(
    package = "tracing",
    version = "0.1.41",
)
crate.spec(
    package = "tracing-futures",
    version = "0.2.5",
)
crate.spec(
    package = "tracing-subscriber",
    version = "0.3.20",
)
crate.spec(
    features = ["axum_extras"],
    package = "utoipa",
    version = "5.4.0",
)
crate.spec(
    features = ["v4"],
    package = "uuid",
    version = "1.18.1",
)

# Dev dependencies
crate.spec(
    features = ["yaml"],
    package = "insta",
    version = "1.43.2",
)
crate.spec(
    package = "mockall",
    version = "0.13.1",
)
crate.spec(
    package = "regex",
    version = "1.11",
)
crate.spec(
    features = ["postgres"],
    package = "testcontainers-modules",
    version = "0.13.0",
)

crate.from_specs()
use_repo(crate, "crates")

# --- OCI Configuration ---
bazel_dep(name = "rules_oci", version = "2.2.6")
oci_extension = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci_extension.pull(
    name = "distroless_cc",
    digest = "sha256:620d8b11ae800f0dbd7995f89ddc5344ad603269ea98770588b1b07a4a0a6872",
    image = "gcr.io/distroless/cc-debian12",
    platforms = [
        "linux/amd64",
    ],
)
use_repo(oci_extension, "distroless_cc", "distroless_cc_linux_amd64")
