"Module file for building projects in lowkeylab"

module(
    name = "bazel-repo",
    version = "0.1.0",
    compatibility_level = 1,
)

# Currently bazel-lib is only load()ed when platforms is used.
bazel_dep(name = "bazel_lib", version = "3.1.1")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")
bazel_dep(name = "aspect_rules_lint", version = "1.13.0")
bazel_dep(name = "aspect_rules_esbuild", version = "0.25.0")
bazel_dep(name = "aspect_rules_js", version = "2.9.2")
bazel_dep(name = "aspect_rules_swc", version = "2.6.1")
bazel_dep(name = "aspect_rules_ts", version = "3.8.3")
bazel_dep(name = "bazelrc-preset.bzl", version = "1.9.2")

# Bazel 9: Ensure transitives don't depend on rules_nodejs prior to
# https://github.com/bazel-contrib/rules_nodejs/commit/1fc6b6b763c4f79994edc9edab10399f7446d8be
bazel_dep(name = "rules_nodejs", version = "6.7.3")
bazel_dep(name = "rules_java", version = "9.3.0")
bazel_dep(name = "rules_kotlin", version = "2.2.2")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.2")
bazel_dep(name = "contrib_rules_jvm", version = "0.32.0")
bazel_dep(name = "container_structure_test", version = "1.22.1")
bazel_dep(name = "rules_multitool", version = "1.11.1")
bazel_dep(name = "rules_oci", version = "2.2.7")
bazel_dep(name = "rules_distroless", version = "0.6.2")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_rust", version = "0.68.1")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_buf", version = "0.5.2")
bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "rules_jvm_external", version = "6.9")
bazel_dep(name = "rules_mypy", version = "0.40.0")
bazel_dep(name = "rules_go", version = "0.59.0")
bazel_dep(name = "tar.bzl", version = "0.8.1")
bazel_dep(name = "toolchains_buildbuddy", version = "0.0.4")

# We have to take a dependency on rules_python in order to set bootstrap=script
# for transitive dependencies, even if there are no Python rules used in this repo.
# See .bazelrc
bazel_dep(name = "rules_python", version = "1.8.3")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "gazelle", version = "0.47.0")

bazel_dep(name = "bazel_env.bzl", version = "0.5.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib_gazelle_plugin", version = "1.9.0", dev_dependency = True)
bazel_dep(name = "gazelle_rust", dev_dependency = True)
git_override(
    module_name = "gazelle_rust",
    commit = "c029702902b753413f80b0549982c32912aa508a",
    remote = "https://github.com/Calsign/gazelle_rust.git",
)

# Use at HEAD version of rules_angular until 0.2.0 is released
bazel_dep(name = "rules_angular")
git_override(
    module_name = "rules_angular",
    commit = "e975faa54a52caa45ff932ec806292ce0988d8d4",
    remote = "https://github.com/devversion/rules_angular.git",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_jar = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_archive(
    name = "net_sourceforge_pmd",
    build_file_content = """java_import(name = "net_sourceforge_pmd", jars = glob(["*.jar"]), visibility = ["//visibility:public"])""",
    sha256 = "21acf96d43cb40d591cacccc1c20a66fc796eaddf69ea61812594447bac7a11d",
    strip_prefix = "pmd-bin-6.55.0/lib",
    url = "https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip",
)

http_jar(
    name = "com_puppycrawl_tools_checkstyle",
    sha256 = "51c34d738520c1389d71998a9ab0e6dabe0d7cf262149f3e01a7294496062e42",
    url = "https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.17.0/checkstyle-10.17.0-all.jar",
)

http_jar(
    name = "google-java-format",
    sha256 = "33068bbbdce1099982ec1171f5e202898eb35f2919cf486141e439fc6e3a4203",
    url = "https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar",
)

http_file(
    name = "pinterest_ktlint",
    executable = True,
    sha256 = "a3fd620207d5c40da6ca789b95e7f823c54e854b7fade7f613e91096a3706d75",
    url = "https://github.com/pinterest/ktlint/releases/download/1.8.0/ktlint",
)

http_jar(
    name = "facebook_ktfmt",
    sha256 = "a493271c137074436a133d72e9e323f91604c97e0c40555629ec39598efead54",
    url = "https://github.com/facebook/ktfmt/releases/download/v0.59/ktfmt-0.59-with-dependencies.jar",
)

#########################
# JavaScript and pnpm package manager

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")

# Allows developers to run the same pnpm version that Bazel manages
use_repo(pnpm, "pnpm")

pnpm.pnpm(
    pnpm_version = "latest",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm",
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
)
use_repo(npm, "npm")

rules_ts_ext = use_extension(
    "@aspect_rules_ts//ts:extensions.bzl",
    "ext",
    dev_dependency = True,
)
rules_ts_ext.deps()
use_repo(rules_ts_ext, "npm_typescript")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node", dev_dependency = True)
node.toolchain(
    node_version = "24.9.0",
)
use_repo(node, "nodejs_toolchains")

#########################
# Fetch tools
# https://blog.aspect.build/run-tools-installed-by-bazel
multitool = use_extension("@rules_multitool//multitool:extension.bzl", "multitool")
multitool.hub(lockfile = "//tools:tools.lock.json")
use_repo(multitool, "multitool")

#########################
# Protobuf and gRPC

buf = use_extension("@rules_buf//buf:extensions.bzl", "buf")
buf.toolchains(
    sha256 = "8d39d81ae5400061bbbb9ce8c2196f039ba04257e9ef5f82de06480a9c5748e0",
    version = "v1.34.0",
)
use_repo(buf, "rules_buf_toolchains")

#########################
# Java and other JVM languages:
# https://github.com/bazelbuild/rules_jvm_external/blob/master/examples/bzlmod/MODULE.bazel
# https://github.com/bazelbuild/rules_jvm_external#pinning-artifacts-and-integration-with-bazels-downloader

# In the Maven support variation, the dependencies are conveniently listed here
# in the MODULE.bazel file.

# Version variables for JVM dependencies
KTOR_VERSION = "3.3.3"

KOTLIN_VERSION = "2.3.0"

POSTGRES_VERSION = "42.7.8"

H2_VERSION = "2.4.240"

EXPOSED_VERSION = "0.61.0"

LOGBACK_VERSION = "1.5.24"

JSON_PATH_VERSION = "2.10.0"

JUNIT_VERSION = "6.0.2"

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        # Ktor dependencies (using -jvm classifier for Kotlin Multiplatform)
        "io.ktor:ktor-client-content-negotiation-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-client-websockets-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-serialization-kotlinx-json-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-call-id-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-call-logging-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-config-yaml-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-content-negotiation-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-core-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-di-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-host-common-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-netty-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-sessions-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-status-pages-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-thymeleaf-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-websockets-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-cors-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-call-id-jvm:%s" % KTOR_VERSION,
        "io.ktor:ktor-server-call-logging-jvm:%s" % KTOR_VERSION,
        # Database dependencies
        "com.h2database:h2:%s" % H2_VERSION,
        "org.jetbrains.exposed:exposed-core:%s" % EXPOSED_VERSION,
        "org.jetbrains.exposed:exposed-dao:%s" % EXPOSED_VERSION,
        "org.jetbrains.exposed:exposed-jdbc:%s" % EXPOSED_VERSION,
        "org.postgresql:postgresql:%s" % POSTGRES_VERSION,
        # Logging
        "ch.qos.logback:logback-classic:%s" % LOGBACK_VERSION,
        # JSON Path
        "com.jayway.jsonpath:json-path:%s" % JSON_PATH_VERSION,
    ],
    fetch_javadoc = True,
    fetch_sources = True,
    known_contributing_modules = [
        "bazel-repo",
        "bazel_worker_java",
        "protobuf",
    ],
    lock_file = "//:maven_install.json",
)
maven.artifact(
    testonly = True,
    artifact = "kotlin-test-junit",
    group = "org.jetbrains.kotlin",
    version = KOTLIN_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "kotlin-test-junit5",
    group = "org.jetbrains.kotlin",
    version = KOTLIN_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "junit-jupiter-api",
    group = "org.junit.jupiter",
    version = JUNIT_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "junit-jupiter-engine",
    group = "org.junit.jupiter",
    version = JUNIT_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "junit-jupiter-params",
    group = "org.junit.jupiter",
    version = JUNIT_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "junit-platform-console",
    group = "org.junit.platform",
    version = JUNIT_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "junit-jupiter",
    group = "org.junit.jupiter",
    version = JUNIT_VERSION,
)
maven.artifact(
    testonly = True,
    artifact = "ktor-server-test-host-jvm",
    group = "io.ktor",
    version = KTOR_VERSION,
)
maven.artifact(
    artifact = "gson",
    force_version = True,
    group = "com.google.code.gson",
    version = "2.13.2",
)
maven.artifact(
    artifact = "error_prone_annotations",
    force_version = True,
    group = "com.google.errorprone",
    version = "2.46.0",
)
maven.artifact(
    artifact = "guava",
    force_version = True,
    group = "com.google.guava",
    version = "33.5.0-jre",
)
use_repo(maven, "maven")

register_toolchains("//:kotlin_toolchain")

#########################
# Rust
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = [
        "1.92.0",
        "nightly/2026-01-11",
    ],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

http_archive(
    name = "swagger_ui",
    build_file = "//3rdparty/swagger_ui:BUILD.swagger_ui",
    integrity = "sha256-SBJE0IEgl7Efuu73n3HZQrFxYX+cn5UU5jrL4T5xzNw=",
    patch_args = [
        "-p1",
    ],
    patches = ["//3rdparty/swagger_ui:fix.patch"],
    strip_prefix = "swagger-ui-5.17.14",
    urls = ["https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.17.14.zip"],
)

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")

inject_repo(crate, "swagger_ui")

crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//:Cargo.toml"],
)
crate.annotation(
    additive_build_file_content = """
filegroup(
    name = "dist",
    srcs = ["@swagger_ui//:dist"],
)
""",
    compile_data = [":dist"],
    crate = "utoipa-swagger-ui",
    gen_build_script = "off",
    patch_args = [
        "-p1",
    ],
    patches = ["//3rdparty/utoipa_swagger_ui:fix.patch"],
    rustc_env = {
        # Set this to make sure that RustEmbed points to the parent dir of the swagger ui dist
        "CARGO_MANIFEST_DIR": "$(execpath :dist)/..",
    },
)
use_repo(crate, "crates")

#########################
# Go
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")

# Download an SDK for the host OS & architecture as well as common remote execution
# platforms, using the version given from the `go.mod` file.
go_sdk.from_file(go_mod = "//:go.mod")
go_sdk.nogo(nogo = "//tools/lint:nogo")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

# All *direct* Go dependencies of the module have to be listed explicitly.
# Run 'bazel mod tidy' to update this
use_repo(go_deps, "com_github_gin_contrib_cors", "com_github_gin_contrib_slog", "com_github_gin_contrib_sse", "com_github_gin_gonic_gin", "com_github_go_delve_delve", "com_github_golang_jwt_jwt_v5", "com_github_golang_migrate_migrate_v4", "com_github_google_uuid", "com_github_hay_kot_scaffold", "com_github_jackc_pgx_v5", "com_github_stretchr_testify", "com_github_testcontainers_testcontainers_go", "com_github_testcontainers_testcontainers_go_modules_postgres", "io_nmyk_cowsay", "org_golang_x_crypto", "org_golang_x_tools", "org_golang_x_tools_gopls", "org_golang_x_vuln")

#########################
# Keep Sorted
keep_sorted_deps = use_extension("@gazelle//:extensions.bzl", "go_deps", isolate = True)
keep_sorted_deps.from_file(go_mod = "@aspect_rules_lint//lint/keep-sorted:go.mod")
use_repo(keep_sorted_deps, "com_github_google_keep_sorted")

##########################
# Container images
oci_extension = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci_extension.pull(
    name = "distroless_cc",
    digest = "sha256:05d26fe67a875592cd65f26b2bcfadb8830eae53e68945784e39b23e62c382e0",
    image = "gcr.io/distroless/cc-debian13",
    platforms = [
        "linux/amd64",
    ],
)
oci_extension.pull(
    name = "distroless_java21",
    digest = "sha256:b93d9330146fb2937d26999f4fe038a7dd5b7d2480508f130f09560ddcb2cd89",
    image = "gcr.io/distroless/java21-debian13",
    platforms = [
        "linux/amd64",
    ],
)
oci_extension.pull(
    name = "distroless_node24",
    digest = "sha256:64cea69417af086d87b7cc75746042fa2528f33cd6e4b49c9fbfe6f97a9a38f0",
    image = "gcr.io/distroless/nodejs24-debian13",
    platforms = [
        "linux/amd64",
    ],
)
oci_extension.pull(
    name = "alpine_caddy",
    digest = "sha256:70e816c44fb79071fc4cd939ffda76e3b629642309efe31a4fb0ed45873be464",
    image = "caddy",
    platforms = [
        "linux/amd64",
    ],
)
use_repo(oci_extension, "alpine_caddy", "alpine_caddy_linux_amd64", "distroless_cc", "distroless_cc_linux_amd64", "distroless_java21", "distroless_java21_linux_amd64", "distroless_node24", "distroless_node24_linux_amd64")

###########################
# BuildBuddy Remote Execution
buildbuddy = use_extension("@toolchains_buildbuddy//:extensions.bzl", "buildbuddy")
buildbuddy.platform(buildbuddy_container_image = "UBUNTU24_04_IMAGE")
