# Points to npm packages (folders with a package.json) within the monorepo.
# See https://pnpm.io/pnpm-workspace_yaml
packages:
  - .
  - angular
  - angular/projects/*
  - angular-ngc
  - angular-ngc/tools
  - angular-ngc/applications/*
  - tools
