// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Circle struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatorID string           `json:"creator_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type CircleMember struct {
	CircleID int32  `json:"circle_id"`
	UserID   string `json:"user_id"`
	Clout    int32  `json:"clout"`
}

type Contest struct {
	ID             int32            `json:"id"`
	CircleID       int32            `json:"circle_id"`
	CreatorID      string           `json:"creator_id"`
	Question       string           `json:"question"`
	Status         string           `json:"status"`
	MinStake       int32            `json:"min_stake"`
	HouseRake      pgtype.Numeric   `json:"house_rake"`
	ResultOptionID pgtype.Int4      `json:"result_option_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	ClosesAt       pgtype.Timestamp `json:"closes_at"`
	Duration       string           `json:"duration"`
}

type Option struct {
	ContestID int32  `json:"contest_id"`
	OptionID  int32  `json:"option_id"`
	Text      string `json:"text"`
}

type Prediction struct {
	ContestID int32            `json:"contest_id"`
	UserID    string           `json:"user_id"`
	OptionID  int32            `json:"option_id"`
	Clout     int32            `json:"clout"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
