// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleMember UserRole = "member"
	UserRoleAdmin  UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Circle struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	CreatorID uuid.UUID `json:"creator_id"`
}

type CircleMember struct {
	CircleID int32     `json:"circle_id"`
	Clout    int32     `json:"clout"`
	UserID   uuid.UUID `json:"user_id"`
}

type Contest struct {
	ID             int32         `json:"id"`
	CircleID       int32         `json:"circle_id"`
	Question       string        `json:"question"`
	Status         string        `json:"status"`
	MinStake       int32         `json:"min_stake"`
	HouseRake      float64       `json:"house_rake"`
	ResultOptionID sql.NullInt32 `json:"result_option_id"`
	CreatedAt      time.Time     `json:"created_at"`
	LockedAt       time.Time     `json:"locked_at"`
	Duration       string        `json:"duration"`
	ExpiresAt      time.Time     `json:"expires_at"`
	CreatorID      uuid.UUID     `json:"creator_id"`
}

type Option struct {
	ContestID int32  `json:"contest_id"`
	OptionID  int32  `json:"option_id"`
	Text      string `json:"text"`
}

type Prediction struct {
	ContestID int32     `json:"contest_id"`
	OptionID  int32     `json:"option_id"`
	Clout     int32     `json:"clout"`
	CreatedAt time.Time `json:"created_at"`
	UserID    uuid.UUID `json:"user_id"`
}

type User struct {
	ID           int32     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
	Uuid         uuid.UUID `json:"uuid"`
}
