// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCircleMember = `-- name: AddCircleMember :exec
INSERT INTO circle_members (circle_id, user_id, clout)
VALUES ($1, $2, $3)
`

type AddCircleMemberParams struct {
	CircleID int32  `json:"circle_id"`
	UserID   string `json:"user_id"`
	Clout    int32  `json:"clout"`
}

func (q *Queries) AddCircleMember(ctx context.Context, arg AddCircleMemberParams) error {
	_, err := q.db.Exec(ctx, addCircleMember, arg.CircleID, arg.UserID, arg.Clout)
	return err
}

const createCircle = `-- name: CreateCircle :one
INSERT INTO circles (name, creator_id, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, creator_id, created_at
`

type CreateCircleParams struct {
	Name      string           `json:"name"`
	CreatorID string           `json:"creator_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error) {
	row := q.db.QueryRow(ctx, createCircle, arg.Name, arg.CreatorID, arg.CreatedAt)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createContest = `-- name: CreateContest :one
INSERT INTO contests (circle_id, creator_id, question, status, min_stake, house_rake, created_at, closes_at, duration)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, circle_id, creator_id, question, status, min_stake, house_rake, result_option_id, created_at, closes_at, duration
`

type CreateContestParams struct {
	CircleID  int32            `json:"circle_id"`
	CreatorID string           `json:"creator_id"`
	Question  string           `json:"question"`
	Status    string           `json:"status"`
	MinStake  int32            `json:"min_stake"`
	HouseRake pgtype.Numeric   `json:"house_rake"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ClosesAt  pgtype.Timestamp `json:"closes_at"`
	Duration  string           `json:"duration"`
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.CircleID,
		arg.CreatorID,
		arg.Question,
		arg.Status,
		arg.MinStake,
		arg.HouseRake,
		arg.CreatedAt,
		arg.ClosesAt,
		arg.Duration,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CreatorID,
		&i.Question,
		&i.Status,
		&i.MinStake,
		&i.HouseRake,
		&i.ResultOptionID,
		&i.CreatedAt,
		&i.ClosesAt,
		&i.Duration,
	)
	return i, err
}

const createOption = `-- name: CreateOption :exec
INSERT INTO options (contest_id, option_id, text)
VALUES ($1, $2, $3)
`

type CreateOptionParams struct {
	ContestID int32  `json:"contest_id"`
	OptionID  int32  `json:"option_id"`
	Text      string `json:"text"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) error {
	_, err := q.db.Exec(ctx, createOption, arg.ContestID, arg.OptionID, arg.Text)
	return err
}

const deleteCircle = `-- name: DeleteCircle :exec
DELETE FROM circles
WHERE id = $1
`

func (q *Queries) DeleteCircle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCircle, id)
	return err
}

const findExpiredContests = `-- name: FindExpiredContests :many
SELECT id, circle_id, creator_id, question, status, min_stake, house_rake, result_option_id, created_at, closes_at, duration FROM contests
WHERE status IN ('OPEN', 'LOCKED')
  AND closes_at <= NOW()
`

func (q *Queries) FindExpiredContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.Query(ctx, findExpiredContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.CreatorID,
			&i.Question,
			&i.Status,
			&i.MinStake,
			&i.HouseRake,
			&i.ResultOptionID,
			&i.CreatedAt,
			&i.ClosesAt,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCircle = `-- name: GetCircle :one
SELECT id, name, creator_id, created_at FROM circles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCircle(ctx context.Context, id int32) (Circle, error) {
	row := q.db.QueryRow(ctx, getCircle, id)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getCircleMember = `-- name: GetCircleMember :one
SELECT circle_id, user_id, clout FROM circle_members
WHERE circle_id = $1 AND user_id = $2 LIMIT 1
`

type GetCircleMemberParams struct {
	CircleID int32  `json:"circle_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetCircleMember(ctx context.Context, arg GetCircleMemberParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, getCircleMember, arg.CircleID, arg.UserID)
	var i CircleMember
	err := row.Scan(&i.CircleID, &i.UserID, &i.Clout)
	return i, err
}

const getContest = `-- name: GetContest :one
SELECT id, circle_id, creator_id, question, status, min_stake, house_rake, result_option_id, created_at, closes_at, duration FROM contests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContest(ctx context.Context, id int32) (Contest, error) {
	row := q.db.QueryRow(ctx, getContest, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CreatorID,
		&i.Question,
		&i.Status,
		&i.MinStake,
		&i.HouseRake,
		&i.ResultOptionID,
		&i.CreatedAt,
		&i.ClosesAt,
		&i.Duration,
	)
	return i, err
}

const listCircleMembers = `-- name: ListCircleMembers :many
SELECT circle_id, user_id, clout FROM circle_members
WHERE circle_id = $1
`

func (q *Queries) ListCircleMembers(ctx context.Context, circleID int32) ([]CircleMember, error) {
	rows, err := q.db.Query(ctx, listCircleMembers, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CircleMember
	for rows.Next() {
		var i CircleMember
		if err := rows.Scan(&i.CircleID, &i.UserID, &i.Clout); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestOptions = `-- name: ListContestOptions :many
SELECT contest_id, option_id, text FROM options
WHERE contest_id = $1
`

func (q *Queries) ListContestOptions(ctx context.Context, contestID int32) ([]Option, error) {
	rows, err := q.db.Query(ctx, listContestOptions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(&i.ContestID, &i.OptionID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestPredictions = `-- name: ListContestPredictions :many
SELECT contest_id, user_id, option_id, clout, created_at FROM predictions
WHERE contest_id = $1
`

func (q *Queries) ListContestPredictions(ctx context.Context, contestID int32) ([]Prediction, error) {
	rows, err := q.db.Query(ctx, listContestPredictions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prediction
	for rows.Next() {
		var i Prediction
		if err := rows.Scan(
			&i.ContestID,
			&i.UserID,
			&i.OptionID,
			&i.Clout,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestsByCircle = `-- name: ListContestsByCircle :many
SELECT id, circle_id, creator_id, question, status, min_stake, house_rake, result_option_id, created_at, closes_at, duration
FROM contests
WHERE circle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContestsByCircle(ctx context.Context, circleID int32) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContestsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.CreatorID,
			&i.Question,
			&i.Status,
			&i.MinStake,
			&i.HouseRake,
			&i.ResultOptionID,
			&i.CreatedAt,
			&i.ClosesAt,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCircles = `-- name: ListUserCircles :many
SELECT c.id, c.name, c.creator_id, c.created_at
FROM circles c
JOIN circle_members cm ON cm.circle_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListUserCircles(ctx context.Context, userID string) ([]Circle, error) {
	rows, err := q.db.Query(ctx, listUserCircles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Circle
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCircleMemberClout = `-- name: UpdateCircleMemberClout :exec
UPDATE circle_members
SET clout = $3
WHERE circle_id = $1 AND user_id = $2
`

type UpdateCircleMemberCloutParams struct {
	CircleID int32  `json:"circle_id"`
	UserID   string `json:"user_id"`
	Clout    int32  `json:"clout"`
}

func (q *Queries) UpdateCircleMemberClout(ctx context.Context, arg UpdateCircleMemberCloutParams) error {
	_, err := q.db.Exec(ctx, updateCircleMemberClout, arg.CircleID, arg.UserID, arg.Clout)
	return err
}

const updateContestStatus = `-- name: UpdateContestStatus :exec
UPDATE contests
SET status = $2, result_option_id = $3
WHERE id = $1
`

type UpdateContestStatusParams struct {
	ID             int32       `json:"id"`
	Status         string      `json:"status"`
	ResultOptionID pgtype.Int4 `json:"result_option_id"`
}

func (q *Queries) UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) error {
	_, err := q.db.Exec(ctx, updateContestStatus, arg.ID, arg.Status, arg.ResultOptionID)
	return err
}

const updateContestStatusOnly = `-- name: UpdateContestStatusOnly :exec
UPDATE contests
SET status = $2
WHERE id = $1
`

type UpdateContestStatusOnlyParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateContestStatusOnly(ctx context.Context, arg UpdateContestStatusOnlyParams) error {
	_, err := q.db.Exec(ctx, updateContestStatusOnly, arg.ID, arg.Status)
	return err
}

const upsertPrediction = `-- name: UpsertPrediction :exec
INSERT INTO predictions (contest_id, user_id, option_id, clout, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (contest_id, user_id, option_id)
DO UPDATE SET clout = EXCLUDED.clout, created_at = EXCLUDED.created_at
`

type UpsertPredictionParams struct {
	ContestID int32            `json:"contest_id"`
	UserID    string           `json:"user_id"`
	OptionID  int32            `json:"option_id"`
	Clout     int32            `json:"clout"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) UpsertPrediction(ctx context.Context, arg UpsertPredictionParams) error {
	_, err := q.db.Exec(ctx, upsertPrediction,
		arg.ContestID,
		arg.UserID,
		arg.OptionID,
		arg.Clout,
		arg.CreatedAt,
	)
	return err
}
