// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddCircleMember(ctx context.Context, arg AddCircleMemberParams) error
	AddContestCircle(ctx context.Context, arg AddContestCircleParams) error
	CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) error
	CreatePrediction(ctx context.Context, arg CreatePredictionParams) (Prediction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCircle(ctx context.Context, id int32) (Circle, error)
	GetCircleMember(ctx context.Context, arg GetCircleMemberParams) (CircleMember, error)
	GetContest(ctx context.Context, id int32) (Contest, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCircleMembers(ctx context.Context, circleID int32) ([]CircleMember, error)
	ListContestCircles(ctx context.Context, contestID int32) ([]ContestCircle, error)
	ListContestOptions(ctx context.Context, contestID int32) ([]Option, error)
	ListContestPredictions(ctx context.Context, contestID int32) ([]Prediction, error)
	ListContestsByCircle(ctx context.Context, circleID int32) ([]Contest, error)
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) error
}

var _ Querier = (*Queries)(nil)
