// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddCircleMember(ctx context.Context, arg AddCircleMemberParams) error
	CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) error
	DeleteCircle(ctx context.Context, id int32) error
	FindExpiredContests(ctx context.Context) ([]Contest, error)
	GetCircle(ctx context.Context, id int32) (Circle, error)
	GetCircleMember(ctx context.Context, arg GetCircleMemberParams) (CircleMember, error)
	GetContest(ctx context.Context, id int32) (Contest, error)
	ListCircleMembers(ctx context.Context, circleID int32) ([]CircleMember, error)
	ListContestOptions(ctx context.Context, contestID int32) ([]Option, error)
	ListContestPredictions(ctx context.Context, contestID int32) ([]Prediction, error)
	ListContestsByCircle(ctx context.Context, circleID int32) ([]Contest, error)
	ListUserCircles(ctx context.Context, userID string) ([]Circle, error)
	UpdateCircleMemberClout(ctx context.Context, arg UpdateCircleMemberCloutParams) error
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) error
	UpdateContestStatusOnly(ctx context.Context, arg UpdateContestStatusOnlyParams) error
	UpsertPrediction(ctx context.Context, arg UpsertPredictionParams) error
}

var _ Querier = (*Queries)(nil)
