// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCircleMember(ctx context.Context, arg AddCircleMemberParams) error
	CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) error
	CreatePrediction(ctx context.Context, arg CreatePredictionParams) (Prediction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCircle(ctx context.Context, id int32) error
	FindContestsToExpire(ctx context.Context) ([]Contest, error)
	FindContestsToLock(ctx context.Context) ([]Contest, error)
	GetCircle(ctx context.Context, id int32) (GetCircleRow, error)
	GetCircleMember(ctx context.Context, arg GetCircleMemberParams) (CircleMember, error)
	GetContest(ctx context.Context, id int32) (Contest, error)
	GetUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCircleMembers(ctx context.Context, circleID int32) ([]ListCircleMembersRow, error)
	ListContestOptions(ctx context.Context, contestID int32) ([]Option, error)
	ListContestPredictions(ctx context.Context, contestID int32) ([]Prediction, error)
	ListContestsByCircle(ctx context.Context, circleID int32) ([]Contest, error)
	ListUserCircles(ctx context.Context, userID uuid.UUID) ([]ListUserCirclesRow, error)
	UpdateCircleMemberClout(ctx context.Context, arg UpdateCircleMemberCloutParams) error
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) error
	UpdateContestStatusOnly(ctx context.Context, arg UpdateContestStatusOnlyParams) error
	UpsertPrediction(ctx context.Context, arg UpsertPredictionParams) error
}

var _ Querier = (*Queries)(nil)
