// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCircleMember = `-- name: AddCircleMember :exec
INSERT INTO circle_members (circle_id, user_id, clout)
VALUES ($1, $2, $3)
`

type AddCircleMemberParams struct {
	CircleID int32 `json:"circle_id"`
	UserID   int32 `json:"user_id"`
	Clout    int32 `json:"clout"`
}

func (q *Queries) AddCircleMember(ctx context.Context, arg AddCircleMemberParams) error {
	_, err := q.db.Exec(ctx, addCircleMember, arg.CircleID, arg.UserID, arg.Clout)
	return err
}

const addContestCircle = `-- name: AddContestCircle :exec
INSERT INTO contest_circles (contest_id, circle_id)
VALUES ($1, $2)
`

type AddContestCircleParams struct {
	ContestID int32 `json:"contest_id"`
	CircleID  int32 `json:"circle_id"`
}

func (q *Queries) AddContestCircle(ctx context.Context, arg AddContestCircleParams) error {
	_, err := q.db.Exec(ctx, addContestCircle, arg.ContestID, arg.CircleID)
	return err
}

const createCircle = `-- name: CreateCircle :one
INSERT INTO circles (name, created_at)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateCircleParams struct {
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error) {
	row := q.db.QueryRow(ctx, createCircle, arg.Name, arg.CreatedAt)
	var i Circle
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createContest = `-- name: CreateContest :one
INSERT INTO contests (creator_id, question, status, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, creator_id, question, status, result_option_id, created_at, expires_at
`

type CreateContestParams struct {
	CreatorID int32            `json:"creator_id"`
	Question  string           `json:"question"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.CreatorID,
		arg.Question,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Question,
		&i.Status,
		&i.ResultOptionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createOption = `-- name: CreateOption :exec
INSERT INTO options (contest_id, option_id, text)
VALUES ($1, $2, $3)
`

type CreateOptionParams struct {
	ContestID int32  `json:"contest_id"`
	OptionID  int32  `json:"option_id"`
	Text      string `json:"text"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) error {
	_, err := q.db.Exec(ctx, createOption, arg.ContestID, arg.OptionID, arg.Text)
	return err
}

const createPrediction = `-- name: CreatePrediction :one
INSERT INTO predictions (contest_id, user_id, option_id, clout, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING contest_id, user_id, option_id, clout, created_at
`

type CreatePredictionParams struct {
	ContestID int32            `json:"contest_id"`
	UserID    int32            `json:"user_id"`
	OptionID  int32            `json:"option_id"`
	Clout     int32            `json:"clout"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreatePrediction(ctx context.Context, arg CreatePredictionParams) (Prediction, error) {
	row := q.db.QueryRow(ctx, createPrediction,
		arg.ContestID,
		arg.UserID,
		arg.OptionID,
		arg.Clout,
		arg.CreatedAt,
	)
	var i Prediction
	err := row.Scan(
		&i.ContestID,
		&i.UserID,
		&i.OptionID,
		&i.Clout,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, role
`

type CreateUserParams struct {
	Username     string   `json:"username"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getCircle = `-- name: GetCircle :one
SELECT id, name, created_at FROM circles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCircle(ctx context.Context, id int32) (Circle, error) {
	row := q.db.QueryRow(ctx, getCircle, id)
	var i Circle
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCircleMember = `-- name: GetCircleMember :one
SELECT circle_id, user_id, clout FROM circle_members
WHERE circle_id = $1 AND user_id = $2 LIMIT 1
`

type GetCircleMemberParams struct {
	CircleID int32 `json:"circle_id"`
	UserID   int32 `json:"user_id"`
}

func (q *Queries) GetCircleMember(ctx context.Context, arg GetCircleMemberParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, getCircleMember, arg.CircleID, arg.UserID)
	var i CircleMember
	err := row.Scan(&i.CircleID, &i.UserID, &i.Clout)
	return i, err
}

const getContest = `-- name: GetContest :one
SELECT id, creator_id, question, status, result_option_id, created_at, expires_at FROM contests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContest(ctx context.Context, id int32) (Contest, error) {
	row := q.db.QueryRow(ctx, getContest, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Question,
		&i.Status,
		&i.ResultOptionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, role FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const listCircleMembers = `-- name: ListCircleMembers :many
SELECT circle_id, user_id, clout FROM circle_members
WHERE circle_id = $1
`

func (q *Queries) ListCircleMembers(ctx context.Context, circleID int32) ([]CircleMember, error) {
	rows, err := q.db.Query(ctx, listCircleMembers, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CircleMember
	for rows.Next() {
		var i CircleMember
		if err := rows.Scan(&i.CircleID, &i.UserID, &i.Clout); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestCircles = `-- name: ListContestCircles :many
SELECT contest_id, circle_id FROM contest_circles
WHERE contest_id = $1
`

func (q *Queries) ListContestCircles(ctx context.Context, contestID int32) ([]ContestCircle, error) {
	rows, err := q.db.Query(ctx, listContestCircles, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestCircle
	for rows.Next() {
		var i ContestCircle
		if err := rows.Scan(&i.ContestID, &i.CircleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestOptions = `-- name: ListContestOptions :many
SELECT contest_id, option_id, text FROM options
WHERE contest_id = $1
`

func (q *Queries) ListContestOptions(ctx context.Context, contestID int32) ([]Option, error) {
	rows, err := q.db.Query(ctx, listContestOptions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(&i.ContestID, &i.OptionID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestPredictions = `-- name: ListContestPredictions :many
SELECT contest_id, user_id, option_id, clout, created_at FROM predictions
WHERE contest_id = $1
`

func (q *Queries) ListContestPredictions(ctx context.Context, contestID int32) ([]Prediction, error) {
	rows, err := q.db.Query(ctx, listContestPredictions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prediction
	for rows.Next() {
		var i Prediction
		if err := rows.Scan(
			&i.ContestID,
			&i.UserID,
			&i.OptionID,
			&i.Clout,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestsByCircle = `-- name: ListContestsByCircle :many
SELECT c.id, c.creator_id, c.question, c.status, c.result_option_id, c.created_at, c.expires_at
FROM contests c
JOIN contest_circles cc ON cc.contest_id = c.id
WHERE cc.circle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContestsByCircle(ctx context.Context, circleID int32) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContestsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Question,
			&i.Status,
			&i.ResultOptionID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContestStatus = `-- name: UpdateContestStatus :exec
UPDATE contests
SET status = $2, result_option_id = $3
WHERE id = $1
`

type UpdateContestStatusParams struct {
	ID             int32       `json:"id"`
	Status         string      `json:"status"`
	ResultOptionID pgtype.Int4 `json:"result_option_id"`
}

func (q *Queries) UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) error {
	_, err := q.db.Exec(ctx, updateContestStatus, arg.ID, arg.Status, arg.ResultOptionID)
	return err
}
