load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

exports_files(glob(["*.sql"]))

filegroup(
    name = "sql_files",
    srcs = glob(["*.sql"]),
)

go_library(
    name = "migrations",
    srcs = ["migrations.go"],
    embedsrcs = glob(["*.sql"]),
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/migrations",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_migrate_migrate_v4//:migrate",
        "@com_github_golang_migrate_migrate_v4//database/postgres",
        "@com_github_golang_migrate_migrate_v4//source/iofs",
    ],
)
