load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "lib",
    srcs = ["lib.rs"],
    proc_macro_deps = ["@crates//:async-trait"],
    deps = ["@crates//:sea-orm-migration"],
)

rust_library(
    name = "m20220101_000001_create_user_table",
    srcs = ["m20220101_000001_create_user_table.rs"],
    proc_macro_deps = ["@crates//:async-trait"],
    deps = ["@crates//:sea-orm-migration"],
)

rust_library(
    name = "m20250618_072946_rename_table_name",
    srcs = ["m20250618_072946_rename_table_name.rs"],
    proc_macro_deps = ["@crates//:async-trait"],
    deps = ["@crates//:sea-orm-migration"],
)

rust_library(
    name = "m20250622_231317_add_index",
    srcs = ["m20250622_231317_add_index.rs"],
    proc_macro_deps = ["@crates//:async-trait"],
    deps = ["@crates//:sea-orm-migration"],
)

rust_library(
    name = "m20250706_102217_add_name_by_server",
    srcs = ["m20250706_102217_add_name_by_server.rs"],
    proc_macro_deps = ["@crates//:async-trait"],
    deps = ["@crates//:sea-orm-migration"],
)

rust_library(
    name = "m20250715_180325_update_unique_column",
    srcs = ["m20250715_180325_update_unique_column.rs"],
    proc_macro_deps = ["@crates//:async-trait"],
    deps = ["@crates//:sea-orm-migration"],
)
