"""
Rules for downloading GitHub releases and creating Bazel repositories.
"""

def _gh_releases_repo_impl(ctx):
    # This dictionary maps the desired target name (module name) to the
    # label of the http_archive repository where it was downloaded.
    # e.g., {"module_a": "@_gh_download_module_a", "module_b": "@_gh_download_module_b"}
    releases = ctx.attr.releases

    build_content = "# Auto-generated by gh_releases_repo\n\n"

    # Create a filegroup for each downloaded release
    for name, repo in releases.items():
        build_content += """
filegroup(
    name = "{name}",
    srcs = ["{repo}//:all_files"],
    visibility = ["//visibility:public"],
)

""".format(
            name = name,
            repo = repo,
        )

    # The filegroup target in http_archive is not guaranteed, so we create one.
    # We also create a BUILD file in each intermediate repository.
    for name, repo in releases.items():
        ctx.file(
            "{repo}/BUILD.bazel".format(repo = repo.replace("@", "")),
            """
filegroup(
    name = "all_files",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
            """,
        )

    ctx.file("BUILD.bazel", build_content)

gh_releases_repo = repository_rule(
    implementation = _gh_releases_repo_impl,
    attrs = {
        "releases": attr.string_dict(),
    },
)
