load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "closer",
    srcs = ["closer.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/contest/closer",
    visibility = ["//predix:__subpackages__"],
)

go_test(
    name = "closer_test",
    timeout = "short",
    srcs = ["closer_test.go"],
    deps = [
        ":closer",
        "@com_github_stretchr_testify//assert",
    ],
)
