load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "closer",
    srcs = ["closer.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/contest/closer",
    visibility = ["//predix:__subpackages__"],
    deps = [
        "//predix/internal/domain/clock",
        "//predix/internal/domain/contest",
        "//predix/internal/domain/contest/repository",
    ],
)

go_test(
    name = "closer_test",
    timeout = "short",
    srcs = ["closer_test.go"],
    deps = [
        ":closer",
        "//predix/internal/domain/circle",
        "//predix/internal/domain/clock",
        "//predix/internal/domain/contest",
        "//predix/internal/domain/contest/repository",
        "//predix/internal/domain/user",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
