load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "core",
    srcs = [
        "game.rs",
        "lib.rs",
        "model.rs",
        "simulation.rs",
    ],
    compile_data = ["Cargo.toml"],
    crate_name = "hearthstone_simulator_core",
    deps = [
        "@crates//:bevy",
        "@crates//:thiserror",
    ],
)

rust_test(
    name = "core_test",
    size = "small",
    crate = ":core",
)
