load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "contest",
    srcs = [
        "contest.go",
        "repository.go",
    ],
    importpath = "github.com/lowkeylab/bazel-repo/predix/domain/contest",
    visibility = ["//visibility:public"],
    deps = [
        "//predix/domain/circle",
        "//predix/domain/user",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "contest_test",
    srcs = ["contest_test.go"],
    deps = [
        ":contest",
        "//predix/domain/circle",
        "//predix/domain/user",
        "@com_github_google_uuid//:uuid",
    ],
)
