load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "contest",
    srcs = ["contest.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/contest",
    visibility = ["//predix:__subpackages__"],
    deps = [
        "//predix/internal/clock",
        "//predix/internal/domain/circle",
        "//predix/internal/domain/user",
    ],
)

go_test(
    name = "contest_test",
    size = "small",
    srcs = ["contest_test.go"],
    tags = [
        # keep
        "requires-docker",
        "requires-network",
    ],
    deps = [
        ":contest",
        "//predix/internal/clock",
        "//predix/internal/domain/circle",
        "//predix/internal/domain/user",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
