load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "app_lib",
    srcs = ["main.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/app",
    visibility = ["//visibility:private"],
    deps = [
        "//predix/core/application",
        "//predix/infrastructure/inmemory",
    ],
)

go_binary(
    name = "app",
    embed = [":app_lib"],
    visibility = ["//visibility:public"],
)
