load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

go_library(
    name = "app_lib",
    srcs = ["main.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/app",
    visibility = ["//visibility:private"],
    deps = [
        "//predix/internal/auth",
        "//predix/internal/clock",
        "//predix/internal/db",
        "//predix/internal/domain/circle/repository",
        "//predix/internal/domain/circle/rest",
        "//predix/internal/domain/circle/service",
        "//predix/internal/domain/contest/closer",
        "//predix/internal/domain/contest/repository",
        "//predix/internal/domain/user/repository",
        "//predix/internal/domain/user/rest",
        "//predix/internal/domain/user/service",
        "//predix/internal/healthcheck",
        "//predix/internal/migrations",
        "@com_github_gin_contrib_cors//:cors",
        "@com_github_gin_contrib_slog//:slog",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_jackc_pgx_v5//stdlib",
    ],
)

go_binary(
    name = "app",
    embed = [":app_lib"],
    visibility = ["//visibility:public"],
)

pkg_tar(
    name = "app_layer",
    srcs = [":app"],
)

oci_image(
    name = "image",
    base = "@distroless_cc",
    entrypoint = ["/app"],
    tars = [
        ":app_layer",
    ],
    visibility = ["//visibility:public"],
)

oci_load(
    name = "load_image",
    image = ":image",
    repo_tags = ["lowkeylab/predix_backend:latest"],
)

oci_push(
    name = "push_image",
    image = ":image",
    remote_tags = ["latest"],
    repository = "ghcr.io/lowkeylab/predix_backend",
    visibility = ["//visibility:public"],
)
