load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "service",
    srcs = ["service.go"],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/user/service",
    visibility = ["//predix:__subpackages__"],
    deps = [
        "//predix/internal/domain/user",
        "//predix/internal/domain/user/repository",
        "@org_golang_x_crypto//bcrypt",
    ],
)

go_test(
    name = "service_test",
    timeout = "short",
    srcs = ["service_test.go"],
    embed = [":service"],
    exec_properties = {
        "test.workload-isolation-type": "firecracker",
        "test.init-dockerd": "true",
    },
    tags = [
        # keep
        "requires-docker",
        "requires-network",
    ],
    deps = [
        "//predix/internal/domain/user",
        "//predix/internal/domain/user/repository",
        "//predix/internal/testutil",
    ],
)
