load("//personal_website/bzl:ts.bzl", "personal_website_ts_library")

personal_website_ts_library(
    name = "utils",
    srcs = [
        "blog.ts",
        "handwriting.ts",
        "seo.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/animejs",
        "//personal_website/src:astro_types",
    ],
)
