load("@rules_rust//rust:toolchain.bzl", "rust_toolchain")

rust_toolchain(
    name = "rust_toolchain_linux_x86_64_impl",
    binary_ext = "",
    cargo = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:cargo",
    cargo_clippy = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:cargo_clippy_bin",
    clippy_driver = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:clippy_driver_bin",
    default_edition = "2024",
    dylib_ext = ".so",
    exec_triple = "x86_64-unknown-linux-gnu",
    # Use the CC toolchain linker (GNU ld) instead of rust-lld
    linker_preference = "cc",
    llvm_cov = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:llvm_cov_bin",
    llvm_lib = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:llvm_lib",
    llvm_profdata = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:llvm_profdata_bin",
    rust_doc = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:rustdoc",
    rust_std = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:rust_std-x86_64-unknown-linux-gnu",
    rustc = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:rustc",
    rustc_lib = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:rustc_lib",
    rustfmt = "@rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools//:rustfmt_bin",
    staticlib_ext = ".a",
    stdlib_linkflags = [
        "-ldl",
        "-lpthread",
    ],
    target_triple = "x86_64-unknown-linux-gnu",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "rust_toolchain_linux_x86_64",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    toolchain = ":rust_toolchain_linux_x86_64_impl",
    toolchain_type = "@rules_rust//rust:toolchain",
    visibility = ["//visibility:public"],
)
