load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "migrations",
    srcs = ["migrations.rs"],
    compile_data = [
        "//nicknamer2/migrations",
    ],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = ["@crates//:sqlx"],
)

rust_test(
    name = "migrations_test",
    timeout = "short",
    crate = ":migrations",
    compile_data = [
        "//nicknamer2/migrations",
    ],
    tags = [
        "requires-network",
    ],
    deps = [
        "@crates//:testcontainers-modules",
        "@crates//:tokio",
    ],
)
