load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//mindrdr:__subpackages__"])

kt_jvm_library(
    name = "mindrdr",
    srcs = glob(["*.kt"]),
    plugins = [
        "//3rdparty/kotlin:serialization_plugin",
    ],
    deps = [
        "//mindrdr/src/main/io/lowkeylab/mindrdr/game",
        "@maven//:io_ktor_ktor_serialization_kotlinx_json_jvm",
        "@maven//:io_ktor_ktor_server_content_negotiation_jvm",
        "@maven//:io_ktor_ktor_server_core_jvm",
        "@maven//:io_ktor_ktor_server_cors_jvm",
        "@maven//:io_ktor_ktor_server_netty_jvm",
        "@maven//:io_ktor_ktor_server_websockets_jvm",
    ],
)
