alias(
    name = "mindreadr",
    actual = "//mindreadr/src/main/io/lowkeylab/mindreadr/app",
)

alias(
    name = "mindreadr_image",
    actual = "//mindreadr/src/main/io/lowkeylab/mindreadr/app:app_image",
)

alias(
    name = "mindreadr_push_image",
    actual = "//mindreadr/src/main/io/lowkeylab/mindreadr/app:push_app_image",
)
