load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "user",
    srcs = ["user.rs"],
    deps = [
        "@crates//:chrono",
        "@crates//:uuid",
    ],
)

rust_test(
    name = "user_test",
    size = "small",
    crate = ":user",
)

rust_library(
    name = "service",
    srcs = ["service.rs"],
    deps = [
        ":repo",
        ":user",
    ],
)

rust_test(
    name = "service_test",
    timeout = "short",
    crate = ":service",
    tags = [
        "requires-network",
    ],
    deps = [
        ":repo",
        ":user",
        "//nicknamer2/migrations",
        "@crates//:sqlx",
        "@crates//:testcontainers-modules",
        "@crates//:tokio",
    ],
)

rust_library(
    name = "repo",
    srcs = ["repo.rs"],
    deps = [
        ":user",
        "@crates//:sqlx",
        "@crates//:thiserror",
    ],
)
