load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("//angular/bzl:ng.bzl", "ng_application", "ng_test", "process_styles")

# aspect:generation_mode update_only
package(default_visibility = ["//visibility:public"])

exports_files([
    "tsconfig.app.json",
    "tsconfig.spec.json",
])

copy_to_bin(
    name = "srcs",
    srcs = glob(
        ["src/**/*"],
        exclude = ["src/styles.css"],
    ),
)

copy_to_bin(
    name = "vitest_config_files",
    srcs = [
        "vitest-base.config.ts",
        "vitest-global-setup.ts",
    ],
)

process_styles(
    name = "processed_styles",
    src = "src/styles.css",
    srcs = glob([
        "src/**/*.html",
        "src/**/*.ts",
    ]),
    out = "src/processed_styles.css",
    deps = [
        "//angular:node_modules/daisyui",
    ],
)

ng_application(
    name = "tailwind-sample",
    srcs = [
        ":processed_styles",
        ":srcs",
    ],
    tailwindcss = True,
    zonejs = True,
    deps = [
        "//angular:node_modules/daisyui",
    ],
)

ng_test(
    name = "test",
    srcs = [
        ":processed_styles",
        ":srcs",
        ":vitest_config_files",
    ],
    tailwindcss = True,
    vitest = True,
    zonejs = True,
    deps = [
        "//angular:node_modules/daisyui",
    ],
)
