load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@aspect_rules_js//js:defs.bzl", "js_run_binary")
load("@npm//angular:@tailwindcss/cli/package_json.bzl", tailwindcss_bin = "bin")
load("@rules_angular//src/architect:ng_application.bzl", "ng_application")
load("@rules_angular//src/architect:ng_test.bzl", "ng_test")

tailwindcss_bin.tailwindcss_binary(
    name = "tailwindcss",
    data = [
        "//angular:node_modules/@tailwindcss/cli",
        "//angular:node_modules/daisyui",
        "//angular:node_modules/tailwindcss",
    ] + glob([
        "src/**/*.html",
        "src/**/*.ts",
    ]),
)

js_run_binary(
    name = "tailwindcss_runner",
    srcs = [
        "src/styles.source.css",
    ],
    outs = ["src/styles_generated.css"],
    args = [
        "--input",
        "angular/projects/mindreadr/src/styles.source.css",
        "--output",
        "angular/projects/mindreadr/src/styles_generated.css",
    ],
    tool = ":tailwindcss",
)

write_source_files(
    name = "write_styles_css",
    files = {
        "src/styles.css": ":tailwindcss_runner",
    },
)

copy_to_bin(
    name = "srcs",
    srcs = glob(
        ["src/**/*"],
        exclude = [
            "src/styles.source.css",  # Don't include source in build
        ],
    ),
)

ng_application(
    name = "mindreadr",
    ng_config = "//angular:ng-config",
    node_modules = "//angular:node_modules",
)

ng_test(
    name = "test",
    size = "small",
    srcs = [":srcs"],
    ng_config = "//angular:ng-config",
    node_modules = "//angular:node_modules",
    tags = ["no-remote-exec"],
)
