load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("//angular/bzl:ng.bzl", "ng_application", "ng_test", "process_styles")

exports_files([
    "tsconfig.app.json",
    "tsconfig.spec.json",
])

copy_to_bin(
    name = "srcs",
    srcs = glob(
        ["src/**/*"],
        exclude = ["src/styles.css"],
    ),
)

copy_to_bin(
    name = "vitest_config_files",
    srcs = [
        "vitest-base.config.ts",
        "vitest-global-setup.ts",
    ],
)

process_styles(
    name = "processed_styles",
    src = "src/styles.css",
    srcs = glob([
        "src/**/*.html",
        "src/**/*.ts",
    ]),
    out = "src/processed_styles.css",
    deps = [
        "//angular:node_modules/daisyui",
    ],
)

js_library(
    name = "canvas_confetti",
    deps = [
        "//angular:node_modules/@types/canvas-confetti",
        "//angular:node_modules/canvas-confetti",
    ],
)

ng_application(
    name = "mindreadr",
    srcs = [
        ":processed_styles",
        ":srcs",
    ],
    tailwindcss = True,
    zonejs = True,
    deps = [
        ":canvas_confetti",
        "//angular:node_modules/daisyui",
    ],
)

ng_test(
    name = "test",
    srcs = [
        ":processed_styles",
        ":srcs",
        ":vitest_config_files",
    ],
    tailwindcss = True,
    vitest = True,
    zonejs = True,
    deps = [
        ":canvas_confetti",
        "//angular:node_modules/daisyui",
    ],
)

pkg_tar(
    name = "caddyfile_layer",
    srcs = ["Caddyfile"],
    package_dir = "/etc/caddy",
)

pkg_tar(
    name = "frontend_layer",
    srcs = [":mindreadr"],
    package_dir = "/app",
    strip_prefix = "dist",
)

oci_image(
    name = "image",
    base = "@alpine_caddy",
    entrypoint = [
        "caddy",
        "run",
        "--config",
        "/etc/caddy/Caddyfile",
    ],
    tars = [
        ":caddyfile_layer",
        ":frontend_layer",
    ],
)

oci_load(
    name = "load_image",
    image = ":image",
    repo_tags = ["lowkeylab/mindreadr_frontend:latest"],
)

oci_push(
    name = "push_image",
    image = ":image",
    remote_tags = ["latest"],
    repository = "ghcr.io/lowkeylab/mindreadr_frontend",
)
