load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_library", "kt_jvm_test")

kt_jvm_library(
    name = "guess_the_word_lib",
    srcs = glob(["src/**/*.kt"]),
    plugins = [
        "//3rdparty/kotlin:serialization_plugin",
    ],
    deps = [
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:com_h2database_h2",
        "@maven//:io_ktor_ktor_serialization_kotlinx_json_jvm",
        "@maven//:io_ktor_ktor_server_content_negotiation_jvm",
        "@maven//:io_ktor_ktor_server_core_jvm",
        "@maven//:io_ktor_ktor_server_netty_jvm",
        "@maven//:io_ktor_ktor_server_status_pages_jvm",
        "@maven//:org_jetbrains_exposed_exposed_core",
        "@maven//:org_jetbrains_exposed_exposed_jdbc",
        "@maven//:org_postgresql_postgresql",
    ],
)

kt_jvm_binary(
    name = "guess_the_word",
    main_class = "io.lowkeylabs.ApplicationKt",
    resource_strip_prefix = "guess_the_word/resources",
    resources = glob([
        "resources/**",
    ]),
    runtime_deps = [":guess_the_word_lib"],
)

test_deps = [
    ":guess_the_word_lib",
    "@maven//:io_ktor_ktor_server_test_host_jvm",
    "@maven//:org_jetbrains_kotlin_kotlin_test",
    "@maven//:org_jetbrains_kotlin_kotlin_test_junit",
    "@maven//:io_ktor_ktor_client_content_negotiation_jvm",
]

kt_jvm_test(
    name = "application_test",
    srcs = ["test/ApplicationTest.kt"],
    test_class = "io.lowkeylabs.ApplicationTest",
    deps = test_deps,
)

kt_jvm_test(
    name = "application_json_path_test",
    srcs = ["test/ApplicationJsonPathTest.kt"],
    test_class = "io.lowkeylabs.ApplicationJsonPathTest",
    deps = test_deps + [
        "@maven//:com_jayway_jsonpath_json_path",
    ],
)
