load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

package_group(
    name = "nicknamer",
    packages = ["//nicknamer/..."],
)

filegroup(
    name = "compose_file",
    srcs = ["compose.yaml"],
)

sh_binary(
    name = "run_locally",
    srcs = ["run_locally.sh"],
    data = [
        ":compose_file",
        "//nicknamer/server/bin/src:main",
    ],
)
