load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "graphql_context",
    srcs = ["context.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        "//nicknamer2/src/auth",
        "//nicknamer2/src/name:name_repo",
        "//nicknamer2/src/name:name_service",
        "@crates//:juniper",
    ],
)

rust_library(
    name = "graphql_relay",
    srcs = ["relay.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        "//nicknamer2/src/name",
        "@crates//:anyhow",
        "@crates//:base64",
        "@crates//:juniper",
        "@crates//:serde",
        "@crates//:serde_json",
    ],
)

rust_test(
    name = "graphql_relay_test",
    crate = ":graphql_relay",
)

rust_library(
    name = "graphql_model",
    srcs = ["model.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        ":graphql_context",
        ":graphql_relay",
        "//nicknamer2/src/name",
        "@crates//:chrono",
        "@crates//:juniper",
    ],
)

rust_library(
    name = "graphql_query",
    srcs = ["query.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        ":graphql_context",
        ":graphql_model",
        ":graphql_relay",
        "//nicknamer2/src/name",
        "@crates//:juniper",
    ],
)

rust_library(
    name = "graphql_mutation",
    srcs = ["mutation.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        ":graphql_context",
        ":graphql_model",
        "//nicknamer2/src/auth:auth_claims",
        "//nicknamer2/src/name",
        "@crates//:juniper",
    ],
)

rust_library(
    name = "graphql_schema",
    srcs = ["schema.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        ":graphql_context",
        ":graphql_mutation",
        ":graphql_query",
        "@crates//:juniper",
    ],
)

rust_library(
    name = "graphql",
    srcs = ["mod.rs"],
    visibility = ["//nicknamer2:__subpackages__"],
    deps = [
        ":graphql_context",
        ":graphql_schema",
    ],
)

rust_test(
    name = "graphql_integration_test",
    timeout = "short",
    srcs = ["tests.rs"],
    tags = ["requires-network"],
    deps = [
        ":graphql_relay",
        ":graphql_schema",
        "//nicknamer2/src/auth",
        "//nicknamer2/src/migrations",
        "//nicknamer2/src/name",
        "//nicknamer2/src/name:name_repo",
        "//nicknamer2/src/name:name_service",
        "//nicknamer2/src/server",
        "@crates//:axum",
        "@crates//:base64",
        "@crates//:chrono",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:testcontainers-modules",
        "@crates//:tokio",
        "@crates//:tower",
        "@crates//:uuid",
    ],
)
