services:
  postgres:
    image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
    environment:
      POSTGRES_DB: nicknamer2
      POSTGRES_USER: nicknamer2
      POSTGRES_PASSWORD: nicknamer2
    ports:
      - "5433:5432"
    volumes:
      - nicknamer2_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nicknamer2 -d nicknamer2"]
      interval: 5s
      timeout: 5s
      retries: 5
  casdoor-db:
    image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
    environment:
      POSTGRES_DB: casdoor
      POSTGRES_USER: casdoor
      POSTGRES_PASSWORD: casdoor
    volumes:
      - casdoor_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casdoor -d casdoor"]
      interval: 5s
      timeout: 5s
      retries: 5
  casdoor:
    image: casbin/casdoor:4.9.0@sha256:bd81919b2a7de13d85b8d5ba77ec85a874df9cb99bd6f11cbab5bdd2bce95c11
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./casdoor/conf:/conf
    depends_on:
      casdoor-db:
        condition: service_healthy
volumes:
  nicknamer2_postgres_data:
  casdoor_postgres_data:
