services:
  postgres:
    image: postgres:18@sha256:cfca8125dc0f78cfdb2088e49d8446aa58e2b2d7fefbf53dc1f04dc44f811a3a
    environment:
      POSTGRES_DB: nicknamer2
      POSTGRES_USER: nicknamer2
      POSTGRES_PASSWORD: nicknamer2
    ports:
      - "5433:5432"
    volumes:
      - nicknamer2_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nicknamer2 -d nicknamer2"]
      interval: 5s
      timeout: 5s
      retries: 5
  casdoor-db:
    image: postgres:18@sha256:cfca8125dc0f78cfdb2088e49d8446aa58e2b2d7fefbf53dc1f04dc44f811a3a
    environment:
      POSTGRES_DB: casdoor
      POSTGRES_USER: casdoor
      POSTGRES_PASSWORD: casdoor
    volumes:
      - casdoor_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casdoor -d casdoor"]
      interval: 5s
      timeout: 5s
      retries: 5
  casdoor:
    image: casbin/casdoor:3.141.0@sha256:e27170d350cab72990d2199d95ce4be433dd683c747db7d54ee94259642a3e1c
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./casdoor/conf:/conf
    depends_on:
      casdoor-db:
        condition: service_healthy
volumes:
  nicknamer2_postgres_data:
  casdoor_postgres_data:
