load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//guess_the_word:pkg_group"])

kt_jvm_library(
    name = "game",
    srcs = glob(["*.kt"]),
    plugins = [
        "//3rdparty/kotlin:serialization_plugin",
    ],
    deps = [
        "//guess_the_word/src/main/io/lowkeylab/guesstheword/player",
        "@maven//:org_jetbrains_kotlinx_kotlinx_serialization_json_jvm",
    ],
)
