load("@rules_rust//rust:defs.bzl", "rust_test_suite")

package(default_visibility = ["//nicknamer"])

rust_test_suite(
    name = "tests",
    size = "small",
    srcs = glob(["*.rs"]),
    data = glob(["snapshots/**/*.snap"]),
    env = {
        "INSTA_UPDATE": "no",
        "INSTA_WORKSPACE_ROOT": ".",
    },
    shared_srcs = glob(["common/**"]),
    tags = ["requires-network"],
    deps = [
        "//nicknamer/migration/lib",
        "//nicknamer/server/lib",
        "@crates//:anyhow",
        "@crates//:askama",
        "@crates//:axum",
        "@crates//:insta",
        "@crates//:sea-orm",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:testcontainers-modules",
        "@crates//:tokio",
        "@crates//:tower",
        "@crates//:tracing-subscriber",
        "@rules_rust//tools/runfiles",
    ],
)
