load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test_suite")

package(default_visibility = ["//nicknamer"])

filegroup(
    name = "templates",
    srcs = glob(["templates/**/*"]),
)

rust_library(
    name = "lib",
    srcs = glob(["src/**/*.rs"]),
    compile_data = [":templates"],
    crate_name = "nicknamer_server",
    deps = [
        "//nicknamer/migration/lib",
        "@crates//:anyhow",
        "@crates//:askama",
        "@crates//:axum",
        "@crates//:axum-extra",
        "@crates//:chrono",
        "@crates//:config",
        "@crates//:jsonwebtoken",
        "@crates//:sea-orm",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:serde_yaml",
        "@crates//:thiserror",
        "@crates//:time",
        "@crates//:tokio",
        "@crates//:tower",
        "@crates//:tower-http",
        "@crates//:tracing",
        "@crates//:tracing-futures",
        "@crates//:tracing-subscriber",
        "@crates//:utoipa",
        "@crates//:utoipa-swagger-ui",
        "@crates//:uuid",
    ],
)

rust_test_suite(
    name = "tests",
    srcs = glob(["tests/**"]),
    shared_srcs = glob(["tests/common/**"]),
    deps = [
        ":lib",
        "//nicknamer/migration/lib",
        "@crates//:anyhow",
        "@crates//:askama",
        "@crates//:axum",
        "@crates//:insta",
        "@crates//:sea-orm",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:testcontainers-modules",
        "@crates//:tokio",
        "@crates//:tower",
        "@crates//:tracing-subscriber",
    ],
)
