load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "repository",
    srcs = [
        "postgres.go",
        "repository.go",
    ],
    importpath = "github.com/lowkeylab/bazel-repo/predix/internal/domain/contest/repository",
    visibility = ["//predix:__subpackages__"],
    deps = [
        "//predix/internal/db",
        "//predix/internal/domain/circle",
        "//predix/internal/domain/contest",
        "//predix/internal/domain/user",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgx_v5//pgtype",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)
