load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "author",
    srcs = ["author.rs"],
    deps = ["@crates//:uuid"],
)

rust_library(
    name = "book",
    srcs = ["book.rs"],
    deps = [
        ":author",
        "@crates//:uuid",
    ],
)

rust_library(
    name = "user",
    srcs = ["user.rs"],
    deps = [
        ":book",
        "@crates//:uuid",
    ],
)

rust_test(
    name = "book_test",
    size = "small",
    crate = ":book",
)
