# BUILD file for Bazel tools and extensions
load("@bazelrc-preset.bzl", "bazelrc_preset")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//angular:@graphql-codegen/cli/package_json.bzl", graphql_codegen = "bin")
load("@npm//tools:@angular/cli/package_json.bzl", angular_cli = "bin")
load("@npm//tools:astro/package_json.bzl", astro = "bin")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

bazelrc_preset(
    name = "preset",
    doc_link_template = "https://registry.build/flag/bazel?filter={flag}",
)

npm_link_all_packages(name = "node_modules")

graphql_codegen.graphql_codegen_binary(name = "graphql-codegen")

angular_cli.ng_binary(name = "ng")

astro.astro_binary(
    name = "astro",
    # prevents modifying the host machine filesystem
    env = {
        "ASTRO_TELEMETRY_DISABLED": "1",
    },
)

sh_binary(
    name = "workspace_status",
    srcs = ["workspace_status.sh"],
)
