load("//bzl:kotlin.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "app",
    size = "small",
    srcs = glob(["*.kt"]),
    test_package = "io.lowkeylab.mindrdr.app",
    runtime_deps = ["//mindrdr/src/test:test_runtime_deps"],
    deps = [
        "//mindrdr/src/main/io/lowkeylab/mindrdr",
        "//mindrdr/src/main/io/lowkeylab/mindrdr/game",
        "@maven//:io_ktor_ktor_client_content_negotiation_jvm",
        "@maven//:io_ktor_ktor_client_websockets_jvm",
        "@maven//:io_ktor_ktor_server_test_host_jvm",
    ],
)
