load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "app_tests",
    size = "small",
    srcs = glob(["*.kt"]),
    args = [
        "execute --select-package io.lowkeylab.mindrdr.app",
    ],
    main_class = "org.junit.platform.console.ConsoleLauncher",
    resources = [
        "//mindrdr/src/main/resources",
    ],
    runtime_deps = ["//mindrdr/src/test:test_runtime_deps"],
    deps = [
        "//mindrdr/src/main/io/lowkeylab/mindrdr",
        "//mindrdr/src/main/io/lowkeylab/mindrdr/game",
        "//mindrdr/src/test:test_deps",
        "@maven//:io_ktor_ktor_client_content_negotiation_jvm",
        "@maven//:io_ktor_ktor_client_websockets_jvm",
        "@maven//:io_ktor_ktor_server_test_host_jvm",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_console",
    ],
)
