load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//mindrdr:__subpackages__"])

kt_jvm_library(
    name = "game",
    srcs = glob(["*.kt"]),
    plugins = [
        "//3rdparty/kotlin:serialization_plugin",
    ],
    deps = [
        "//mindrdr/src/main/io/lowkeylab/mindrdr/player",
        "@maven//:org_jetbrains_kotlinx_kotlinx_serialization_json_jvm",
    ],
)
