// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCircleMember(ctx context.Context, arg AddCircleMemberParams) error
	CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) error
	CreatePrediction(ctx context.Context, arg CreatePredictionParams) (Prediction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCircle(ctx context.Context, id uuid.UUID) (Circle, error)
	GetCircleByInviteCode(ctx context.Context, inviteCode string) (Circle, error)
	GetCircleMember(ctx context.Context, arg GetCircleMemberParams) (CircleMember, error)
	GetContest(ctx context.Context, id uuid.UUID) (Contest, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListCircleMembers(ctx context.Context, circleID uuid.UUID) ([]CircleMember, error)
	ListContestOptions(ctx context.Context, contestID uuid.UUID) ([]Option, error)
	ListContestPredictions(ctx context.Context, contestID uuid.UUID) ([]Prediction, error)
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) error
}

var _ Querier = (*Queries)(nil)
