load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "flipped",
    srcs = [
        "card.rs",
        "deck.rs",
        "error.rs",
        "id.rs",
        "lib.rs",
        "participant.rs",
        "session.rs",
    ],
    crate_name = "flipped",
    crate_root = "lib.rs",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:thiserror",
        "@crates//:uuid",
    ],
)

rust_test(
    name = "flipped_test",
    size = "small",
    crate = ":flipped",
    visibility = ["//visibility:public"],
    deps = ["@crates//:googletest"],
)
