load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("//angular/bzl:ng.bzl", "ng_application", "ng_test")

# aspect:generation_mode update_only
package(default_visibility = ["//visibility:public"])

copy_to_bin(
    name = "srcs",
    srcs = glob(
        ["src/**/*"],
        exclude = ["dist/"],
    ),
)

ng_application(
    name = "nicknamer",
    zonejs = True,
)

ng_test(
    name = "test",
    srcs = [":srcs"],
    karma = True,
    zonejs = True,
)
