load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "api",
    srcs = ["api.rs"],
    deps = [
        "@crates//:axum",
        "@crates//:serde",
        "@crates//:tower",
        "@crates//:utoipa",
        "@crates//:utoipa-swagger-ui",
    ],
)

rust_library(
    name = "mod",
    srcs = ["mod.rs"],
    deps = [
        "@crates//:anyhow",
        "@crates//:askama",
        "@crates//:axum",
        "@crates//:migration",
        "@crates//:sea-orm",
        "@crates//:thiserror",
        "@crates//:tokio",
        "@crates//:tower",
        "@crates//:tower-http",
        "@crates//:tracing",
    ],
)
