name: Coverage
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  MISE_EXPERIMENTAL: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@d68576867819dfdec2cf9586a68795f81461da3e
        with:
          bazelisk-cache: true
          bazelrc: |
            common --config=ci
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
            test --test_env=XDG_CACHE_HOME
      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: browser-actions/setup-chrome@b94431e051d1c52dcbe9a7092a4f10f827795416
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Run Coverage
        run: bazel run //tools/coverage -- //...
      - name: Upload to Codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
        with:
          files: coverage-report.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
