name: Deploy
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
on:
  workflow_run:
    workflows: ["Bazel Tests"]
    types:
      - completed
    branches: [main]
env:
  MISE_EXPERIMENTAL: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@dbfe7273a965a5cab150f4e8d5e63d5468018def
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          bazelrc: |
            common --config=ci
            common --compilation_mode=opt
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Log in to GHCR
        uses: docker/login-action@916386b00027d425839f8da46d302dab33f5875b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push All Images
        run: bazel query 'kind("oci_push rule", //...)' | xargs -n 1 bazel run --compilation_mode=opt
