name: Bazel Tests
permissions:
  contents: read
  pull-requests: write
  packages: write
  attestations: write
  id-token: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  MISE_EXPERIMENTAL: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@92148bb48b9a0c5458c53dd0b368fbfbfbaa3210
        with:
          determinate: true
          trust-runner-user: true
          extra-conf: |
            experimental-features = nix-command flakes
      - name: Configure Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
      - uses: bazel-contrib/setup-bazel@d68576867819dfdec2cf9586a68795f81461da3e
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          bazelrc: |
            common --config=ci
            common:lint --config=ci-lint
            common --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
            test --test_env=XDG_CACHE_HOME
      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: browser-actions/setup-chrome@b94431e051d1c52dcbe9a7092a4f10f827795416
      - name: Install Aspect from flake
        run: |
          nix build .#aspect
          install -Dm755 ./result/bin/aspect /usr/local/bin/aspect
      - name: Run Bazel Lints
        run: |
          aspect lint //...
      - name: Run Bazel tests (remote)
        run: |
          bazel test //... --config=ci-remote
