name: Bazel Tests

permissions:
  contents: read
  pull-requests: write
  packages: write
  attestations: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MISE_EXPERIMENTAL: true

jobs:
  ci:
    runs-on: ubuntu-22.04 # glibc version 2.36 is required for base distroless image
    steps:
      - uses: actions/checkout@v5
      
      - uses: jdx/mise-action@b7800bbdc86cc07cbd08204366859657ca5bd6f0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run Bazel tests
        run: bazel test //... --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY}
        env: 
          BUILDBUDDY_API_KEY: ${{secrets.BUILDBUDDY_API_KEY}}
