name: Bazel Tests
permissions:
  contents: read
  pull-requests: write
  packages: write
  attestations: write
  id-token: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  MISE_EXPERIMENTAL: true
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-bazel-ci
        with:
          buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
          docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Check formatting
        env:
          ASPECT_API_TOKEN: ${{ secrets.ASPECT_API_TOKEN }}
        run: |
          aspect format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-bazel-ci
        with:
          buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
          docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Run Bazel Lints
        env:
          ASPECT_API_TOKEN: ${{ secrets.ASPECT_API_TOKEN }}
        run: |
          aspect lint //...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-bazel-ci
        with:
          buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
          docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Run Bazel tests
        env:
          ASPECT_API_TOKEN: ${{ secrets.ASPECT_API_TOKEN }}
        run: |
          aspect test //...
