name: Update Multitool
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v3
        with:
          private-key: ${{ secrets.automation_private_key }}
          app-id: ${{ secrets.automation_app_id }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.get_token.outputs.token }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@92148bb48b9a0c5458c53dd0b368fbfbfbaa3210
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      - name: Configure Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
      - name: Update multitool lockfile
        run: nix develop --command bazel run @multitool//tools/multitool:cwd -- --lockfile tools/tools.lock.json update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ steps.get_token.outputs.token }}
          sign-commits: true
          commit-message: "chore(deps): update multitool managed tools"
          title: "chore(deps): update multitool managed tools"
          body: Automated update of tools managed by multitool.
          branch: automated/update-multitool
          labels: dependencies
