name: Update Multitool
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@d68576867819dfdec2cf9586a68795f81461da3e
        with:
          bazelisk-cache: true
      - name: Update multitool lockfile
        run: bazel run @multitool//tools/multitool:cwd -- --lockfile tools/tools.lock.json update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          commit-message: "chore(deps): update multitool managed tools"
          title: "chore(deps): update multitool managed tools"
          body: Automated update of tools managed by multitool.
          branch: automated/update-multitool
          labels: dependencies
