ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ io.lowkeylab.mindreadr.app.ApplicationKt.module ]
    }
}

cors {
  allowedOrigins = [ "http://localhost:4200"]
  extraAllowedOrigins = ""
  extraAllowedOrigins = ${?CORS_ALLOWED_ORIGINS}
}
